import './globals.css';
import { Josefin_Sans } from 'next/font/google';
import { Header } from '@/components';

// const geistSans = localFont({
// 	src: './fonts/GeistVF.woff',
// 	variable: '--font-geist-sans',
// 	weight: '100 900',
// });
const josefin = Josefin_Sans({
	subset: ['latin'],
	display: 'swap',
});

export const metadata = {
	title: 'World Oasis',
	description: 'Generated by ...',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body
				className={`${josefin.className} antialiased bg-primary-950 text-primary-100 min-h-screen flex flex-col`}
			>
				<Header />
				<div className='flex-1 px-8 py-12 grid'>
					<main className='max-w-7xl mx-auto w-full'>{children}</main>
				</div>
			</body>
		</html>
	);
}
