import localFont from 'next/font/local';
import './globals.css';
import Navigation from '@/components/reusables/Navigation';
import Logo from '@/components/reusables/Logo';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata = {
	title: 'World Oasis',
	description: 'Generated by ...',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased bg-primary-950 text-primary-100 min-h-screen`}
			>
				<div>
					<Navigation />
					<Logo />
				</div>
				<main>{children}</main>
			</body>
		</html>
	);
}
